# Generated by Django 5.2 on 2026-05-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
